#!/bin/bash
#
# build-bins.sh
# Cross-compiles media-mux-controller and creates pre-built tarball
#
# Usage: ./build-bins.sh [VERSION]
#   VERSION: Version string (default: 01)
#
# Output: bins/media-mux-bins-VERSION-arm64.tar.gz
#
# Requirements:
#   - aarch64-linux-gnu-gcc (cross-compiler)
#   - npm (for kodisync dependencies)
#

set -e

VERSION="${1:-01}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build-tmp"
OUTPUT_DIR="$SCRIPT_DIR/bins"
TARBALL_NAME="media-mux-bins-${VERSION}-arm64.tar.gz"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[build-bins]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

log "=============================================="
log "Media-Mux Binary Package Builder"
log "=============================================="
log "Version: $VERSION"
log "Output: $OUTPUT_DIR/$TARBALL_NAME"
echo ""

#------------------------------------------------------------------------------
# Check prerequisites
#------------------------------------------------------------------------------
log "Checking prerequisites..."

if ! command -v aarch64-linux-gnu-gcc &> /dev/null; then
    error "aarch64-linux-gnu-gcc not found. Install with: sudo pacman -S aarch64-linux-gnu-gcc"
fi

if ! command -v npm &> /dev/null; then
    error "npm not found. Install nodejs/npm first."
fi

if [ ! -f "$SCRIPT_DIR/media-mux-controller.c" ]; then
    error "media-mux-controller.c not found. Run from media-mux directory."
fi

if [ ! -d "$SCRIPT_DIR/kodisync" ] || [ ! -f "$SCRIPT_DIR/kodisync/package.json" ]; then
    error "kodisync submodule not found. Run: git submodule update --init"
fi

log "Prerequisites OK"
echo ""

#------------------------------------------------------------------------------
# Prepare build directory
#------------------------------------------------------------------------------
log "Preparing build directory..."
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
mkdir -p "$OUTPUT_DIR"

#------------------------------------------------------------------------------
# Cross-compile media-mux-controller
#------------------------------------------------------------------------------
log "Cross-compiling media-mux-controller for ARM64..."
aarch64-linux-gnu-gcc -O2 -static \
    "$SCRIPT_DIR/media-mux-controller.c" \
    -o "$BUILD_DIR/media-mux-controller"

# Verify it's ARM64
FILE_TYPE=$(file "$BUILD_DIR/media-mux-controller")
if [[ "$FILE_TYPE" != *"aarch64"* ]] && [[ "$FILE_TYPE" != *"ARM aarch64"* ]]; then
    error "Compilation failed - not an ARM64 binary: $FILE_TYPE"
fi
log "Compiled: $(ls -lh "$BUILD_DIR/media-mux-controller" | awk '{print $5}')"

#------------------------------------------------------------------------------
# Install kodisync dependencies
#------------------------------------------------------------------------------
log "Installing kodisync dependencies (production only)..."
cp -r "$SCRIPT_DIR/kodisync" "$BUILD_DIR/kodisync"
cd "$BUILD_DIR/kodisync"
npm install --production --silent
# Remove unnecessary files
rm -rf .git .gitignore
cd "$SCRIPT_DIR"
log "kodisync node_modules: $(du -sh "$BUILD_DIR/kodisync/node_modules" | cut -f1)"

#------------------------------------------------------------------------------
# Copy shell scripts and config files
#------------------------------------------------------------------------------
log "Copying scripts and configuration files..."

# Shell scripts
cp "$SCRIPT_DIR/media-mux-sync-kodi-players.sh" "$BUILD_DIR/"
cp "$SCRIPT_DIR/media-mux-first-boot.sh" "$BUILD_DIR/"
cp "$SCRIPT_DIR/media-mux-autoplay-master.sh" "$BUILD_DIR/" 2>/dev/null || warn "media-mux-autoplay-master.sh not found"
cp "$SCRIPT_DIR/media-mux-autoplay-slave.sh" "$BUILD_DIR/" 2>/dev/null || warn "media-mux-autoplay-slave.sh not found"
cp "$SCRIPT_DIR/stress-test-sync.sh" "$BUILD_DIR/" 2>/dev/null || true

# rc.local variants
cp "$SCRIPT_DIR/rc.local" "$BUILD_DIR/" 2>/dev/null || warn "rc.local not found"
cp "$SCRIPT_DIR/rc.local.master" "$BUILD_DIR/" 2>/dev/null || warn "rc.local.master not found"
cp "$SCRIPT_DIR/rc.local.auto" "$BUILD_DIR/" 2>/dev/null || warn "rc.local.auto not found"

# Kodi configuration
cp "$SCRIPT_DIR/sources.xml" "$BUILD_DIR/" 2>/dev/null || warn "sources.xml not found"
cp "$SCRIPT_DIR/guisettings.xml" "$BUILD_DIR/" 2>/dev/null || warn "guisettings.xml not found"

# Avahi publish script (placeholder - will be regenerated on first boot)
cat > "$BUILD_DIR/avahi-publish-media-mux.sh" << 'EOF'
#!/bin/sh
# Placeholder - will be regenerated by media-mux-first-boot.sh with MAC-based hostname
MY_ID_STRING="media-mux-auto"
MY_ID_PORT=80
MY_ID_SERVICE="_http._tcp"
MY_ID_HW=$(ifconfig |grep -A1 eth0 |grep inet | awk '{print $2}')
avahi-publish-service -s "$MY_ID_STRING [$MY_ID_HW]" $MY_ID_SERVICE $MY_ID_PORT
EOF
chmod +x "$BUILD_DIR/avahi-publish-media-mux.sh"

# Make all scripts executable
chmod +x "$BUILD_DIR"/*.sh 2>/dev/null || true

#------------------------------------------------------------------------------
# Create version file
#------------------------------------------------------------------------------
log "Creating version file..."
cat > "$BUILD_DIR/VERSION" << EOF
MEDIA_MUX_BINS_VERSION=$VERSION
BUILD_DATE=$(date -u +%Y-%m-%d_%H:%M:%S_UTC)
BUILD_HOST=$(hostname)
ARCH=arm64
EOF

#------------------------------------------------------------------------------
# Create tarball
#------------------------------------------------------------------------------
log "Creating tarball..."
cd "$BUILD_DIR"
tar -czvf "$OUTPUT_DIR/$TARBALL_NAME" \
    media-mux-controller \
    kodisync/ \
    media-mux-sync-kodi-players.sh \
    media-mux-first-boot.sh \
    avahi-publish-media-mux.sh \
    media-mux-autoplay-master.sh \
    media-mux-autoplay-slave.sh \
    rc.local \
    rc.local.master \
    rc.local.auto \
    sources.xml \
    guisettings.xml \
    VERSION \
    2>/dev/null || true

cd "$SCRIPT_DIR"

#------------------------------------------------------------------------------
# Cleanup
#------------------------------------------------------------------------------
log "Cleaning up build directory..."
rm -rf "$BUILD_DIR"

#------------------------------------------------------------------------------
# Summary
#------------------------------------------------------------------------------
echo ""
log "=============================================="
log "Build complete!"
log "=============================================="
log "Output: $OUTPUT_DIR/$TARBALL_NAME"
log "Size: $(ls -lh "$OUTPUT_DIR/$TARBALL_NAME" | awk '{print $5}')"
echo ""
log "Contents:"
tar -tzvf "$OUTPUT_DIR/$TARBALL_NAME"
echo ""
log "To test extraction:"
echo "  mkdir -p /tmp/test-extract && tar -xzvf $OUTPUT_DIR/$TARBALL_NAME -C /tmp/test-extract"
echo ""
log "To commit to repo:"
echo "  git add $OUTPUT_DIR/$TARBALL_NAME"
echo "  git commit -m \"add pre-compiled media-mux-bins v$VERSION\""
